###############################################################################
# General Configuration
###############################################################################
version: 1.3.{build}

###############################################################################
# Environment Configuration
###############################################################################
image: Visual Studio 2022

configuration: 
  - Release
  - Debug
platform: 
  - x86
environment:
  matrix:
  - solution_name: VYGE/IDE/VS/VYGE.sln

###############################################################################
# Build Configuration
###############################################################################
build:
  parallel: true
  verbosity: normal

build_script:
  - msbuild %solution_name%
